// Helpers to generate portrait HTML
function _heroImg(seed) {
  return `<img src="https://api.dicebear.com/7.x/adventurer/svg?seed=${seed}" style="width:100%;height:100%;object-fit:cover;border-radius:50%;" draggable="false">`;
}
function _bossImg(seed) {
  return `<img src="https://api.dicebear.com/7.x/bottts/svg?seed=${seed}" style="width:100%;height:100%;object-fit:cover;border-radius:50%;" draggable="false">`;
}

const CONFIG = {

  game: {
    roundsPerBattle: 3,
    levelBonuses: {
      hpPerLevel: 5,
      damagePerLevel: 1,
      attackPerLevel: 1,
    },
    xpThresholds: [0, 200, 500, 900, 1400],
    xpRewards: {
      killVillain: 300,
      damageDealt: 1,
      healingDone: 1,
      surviveRound: 50,
    },
    awardValues: {
      berserker: 150,
      guardian: 120,
      unbreakable: 100,
      teamPlayer: 100,
      precision: 80,
      idlePenalty: -50,
    },
    initiativeBonuses: {
      paladin: 1,
      bard: 3,
      cleric: 2,
      ranger: 4,
      rogue: 5,
    },
  },

  characters: [
    {
      id: 'paladin',
      name: 'Паладин',
      maxHp: 30,
      hp: 30,
      ac: 18,
      attackBonus: 5,
      startX: 80,
      startY: 100,
      color: '#c8a000',
      portraitSvg: _heroImg('paladin'),
      abilities: [
        {
          id: 'holy_strike',
          name: 'Священный удар',
          type: 'attack',
          diceType: 'd8',
          diceCount: 1,
          bonus: 3,
          formula: '1d8 + 3',
          label: 'Бросьте 1d8 + 3 — урон Священного удара',
          description: 'Атака с уроном от святой силы',
          requiresHitCheck: true,
          targetType: 'villain',
        },
        {
          id: 'lay_on_hands',
          name: 'Возложение рук',
          type: 'heal',
          healAmount: 10,
          label: 'Исцеление: +10 HP',
          description: 'Восстанавливает 10 HP союзнику',
          requiresHitCheck: false,
          targetType: 'ally',
        },
        {
          id: 'protection_aura',
          name: 'Аура защиты',
          type: 'buff',
          buffStat: 'ac',
          buffAmount: 2,
          turnsLeft: 1,
          label: 'Аура защиты: +2 AC на 1 ход',
          description: '+2 AC союзнику на 1 ход',
          requiresHitCheck: false,
          targetType: 'ally',
        },
        {
          id: 'divine_shield',
          name: 'Щит веры',
          type: 'buff',
          buffStat: 'damageReduction',
          buffAmount: 3,
          turnsLeft: 2,
          label: 'Щит веры: -3 урона на 2 хода',
          description: 'Уменьшает получаемый урон на 3 на 2 хода',
          requiresHitCheck: false,
          targetType: 'self',
        },
      ],
    },

    {
      id: 'bard',
      name: 'Бард',
      maxHp: 22,
      hp: 22,
      ac: 13,
      attackBonus: 3,
      startX: 80,
      startY: 220,
      color: '#9b59b6',
      portraitSvg: _heroImg('bard'),
      abilities: [
        {
          id: 'sharp_word',
          name: 'Острое словцо',
          type: 'attack_debuff',
          diceType: 'd4',
          diceCount: 1,
          bonus: 1,
          formula: '1d4 + 1',
          label: 'Бросьте 1d4 + 1 — урон Острого словца',
          description: 'Атака + дебафф -2 к атаке цели на 1 ход',
          requiresHitCheck: true,
          targetType: 'villain',
          debuffStat: 'attackBonus',
          debuffAmount: -2,
          debuffTurns: 1,
        },
        {
          id: 'word_of_recovery',
          name: 'Слово исцеления',
          type: 'heal',
          healAmount: 6,
          label: 'Слово исцеления: +6 HP',
          description: 'Восстанавливает 6 HP союзнику',
          requiresHitCheck: false,
          targetType: 'ally',
        },
        {
          id: 'inspiration',
          name: 'Вдохновение',
          type: 'buff',
          diceType: 'd6',
          diceCount: 1,
          buffStat: 'attackBonus',
          label: 'Бросьте 1d6 — бонус Вдохновения',
          description: '+1d6 к атаке союзника на 1 ход',
          requiresHitCheck: false,
          targetType: 'ally',
          turnsLeft: 1,
          needsRoll: true,
        },
        {
          id: 'dissonant_whispers',
          name: 'Диссонанс',
          type: 'debuff',
          debuffStat: 'ac',
          debuffAmount: -3,
          debuffTurns: 2,
          label: 'Диссонанс: -3 AC злодею на 2 хода',
          description: 'Снижает AC злодея на 3 на 2 хода',
          requiresHitCheck: false,
          targetType: 'villain',
        },
      ],
    },

    {
      id: 'cleric',
      name: 'Клирик',
      maxHp: 26,
      hp: 26,
      ac: 15,
      attackBonus: 4,
      startX: 80,
      startY: 340,
      color: '#3498db',
      portraitSvg: _heroImg('cleric'),
      abilities: [
        {
          id: 'holy_fire',
          name: 'Священный огонь',
          type: 'attack_no_miss',
          diceType: 'd6',
          diceCount: 1,
          bonus: 2,
          formula: '1d6 + 2',
          label: 'Бросьте 1d6 + 2 — урон Священного огня (игнорирует AC)',
          description: 'Всегда попадает, игнорирует AC',
          requiresHitCheck: false,
          targetType: 'villain',
        },
        {
          id: 'heal_wounds',
          name: 'Исцеление ран',
          type: 'heal',
          healAmount: 14,
          label: 'Исцеление ран: +14 HP',
          description: 'Восстанавливает 14 HP союзнику',
          requiresHitCheck: false,
          targetType: 'ally',
        },
        {
          id: 'blessing',
          name: 'Благословение',
          type: 'buff',
          diceType: 'd4',
          diceCount: 1,
          buffStat: 'attackBonus',
          label: 'Бросьте 1d4 — бонус Благословения',
          description: '+1d4 к атаке союзнику на 2 хода',
          requiresHitCheck: false,
          targetType: 'ally',
          turnsLeft: 2,
          needsRoll: true,
        },
        {
          id: 'mass_heal',
          name: 'Массовое лечение',
          type: 'heal_all',
          healAmount: 5,
          label: 'Массовое лечение: +5 HP всем героям',
          description: 'Восстанавливает 5 HP всем живым героям',
          requiresHitCheck: false,
          targetType: 'all_allies',
        },
      ],
    },

    {
      id: 'ranger',
      name: 'Рейнджер',
      maxHp: 24,
      hp: 24,
      ac: 14,
      attackBonus: 6,
      startX: 80,
      startY: 460,
      color: '#27ae60',
      portraitSvg: _heroImg('ranger'),
      abilities: [
        {
          id: 'precise_shot',
          name: 'Точный выстрел',
          type: 'attack',
          diceType: 'd10',
          diceCount: 1,
          bonus: 4,
          formula: '1d10 + 4',
          label: 'Бросьте 1d10 + 4 — урон Точного выстрела',
          description: 'Мощный точный выстрел',
          requiresHitCheck: true,
          targetType: 'villain',
        },
        {
          id: 'hunters_mark',
          name: 'Метка охотника',
          type: 'debuff_bonus',
          debuffStat: 'bonusDamage',
          bonusDiceType: 'd6',
          bonusDiceCount: 1,
          debuffTurns: 1,
          label: 'Метка охотника: следующий удар по цели +1d6 урона',
          description: '+1d6 к следующему урону по этой цели',
          requiresHitCheck: false,
          targetType: 'villain',
        },
        {
          id: 'camouflage',
          name: 'Камуфляж',
          type: 'buff',
          buffStat: 'damageReduction',
          buffAmount: 4,
          turnsLeft: 2,
          label: 'Камуфляж: -4 урона от атак на 2 хода',
          description: 'Уменьшает получаемый урон на 4 на 2 хода',
          requiresHitCheck: false,
          targetType: 'self',
        },
        {
          id: 'multi_shot',
          name: 'Двойной выстрел',
          type: 'attack',
          diceType: 'd6',
          diceCount: 2,
          bonus: 2,
          formula: '2d6 + 2',
          label: 'Бросьте 2d6 + 2 — урон Двойного выстрела',
          description: 'Два быстрых выстрела',
          requiresHitCheck: true,
          targetType: 'villain',
        },
      ],
    },

    {
      id: 'rogue',
      name: 'Плут',
      maxHp: 20,
      hp: 20,
      ac: 14,
      attackBonus: 4,
      startX: 80,
      startY: 580,
      color: '#e74c3c',
      portraitSvg: _heroImg('rogue'),
      abilities: [
        {
          id: 'sneak_attack',
          name: 'Скрытая атака',
          type: 'attack',
          diceType: 'd6',
          diceCount: 2,
          bonus: 2,
          formula: '2d6 + 2',
          label: 'Бросьте 2d6 + 2 — урон Скрытой атаки',
          description: 'Мощный удар из тени (1 раз за раунд)',
          requiresHitCheck: true,
          targetType: 'villain',
          oncePerRound: true,
        },
        {
          id: 'evasion',
          name: 'Уклонение',
          type: 'buff',
          buffStat: 'halfDamage',
          buffAmount: 1,
          turnsLeft: 1,
          label: 'Уклонение: половина урона на 1 ход',
          description: 'Все атаки наносят половину урона на 1 ход',
          requiresHitCheck: false,
          targetType: 'self',
        },
        {
          id: 'weak_point',
          name: 'Уязвимое место',
          type: 'debuff',
          debuffStat: 'ac',
          debuffAmount: -3,
          debuffTurns: 2,
          label: 'Уязвимое место: -3 AC злодею на 2 хода',
          description: 'Обнаруживает слабину в броне цели',
          requiresHitCheck: false,
          targetType: 'villain',
        },
        {
          id: 'poisoned_blade',
          name: 'Отравленный клинок',
          type: 'attack',
          diceType: 'd4',
          diceCount: 2,
          bonus: 3,
          formula: '2d4 + 3',
          label: 'Бросьте 2d4 + 3 — урон Отравленного клинка',
          description: 'Атака ядом',
          requiresHitCheck: true,
          targetType: 'villain',
        },
      ],
    },
  ],

  maps: [
    {
      id: 'map1',
      name: 'Логово бандитов',
      background: '#1a1008',
      gridColor: 'rgba(180, 120, 40, 0.15)',
      boss: {
        id: 'bandit_leader',
        name: 'Вожак бандитов',
        maxHp: 60,
        hp: 60,
        ac: 12,
        actionsPerRound: 2,
        attackBonus: 4,
        canFlee: true,
        startX: 820,
        startY: 360,
        color: '#8a5a2a',
        portraitSvg: _bossImg('bandit'),
        abilities: [
          {
            id: 'heavy_strike',
            name: 'Тяжёлый удар',
            type: 'attack',
            diceType: 'd8',
            diceCount: 1,
            bonus: 3,
            formula: '1d8 + 3',
            label: 'Бросьте 1d8 + 3 — урон Тяжёлого удара',
            requiresHitCheck: true,
            targetType: 'hero',
            actionCost: 1,
          },
          {
            id: 'berserker_rage',
            name: 'Берсерк',
            type: 'attack',
            diceType: 'd12',
            diceCount: 1,
            bonus: 5,
            formula: '1d12 + 5',
            label: 'Бросьте 1d12 + 5 — урон Удара берсерка',
            requiresHitCheck: true,
            targetType: 'hero',
            actionCost: 2,
          },
          {
            id: 'battle_cry',
            name: 'Боевой клич',
            type: 'self_buff',
            buffStat: 'attackBonus',
            buffAmount: 2,
            turnsLeft: 1,
            label: 'Боевой клич: +2 к атаке на 1 ход',
            requiresHitCheck: false,
            targetType: 'self',
            actionCost: 1,
          },
        ],
      },
    },
    {
      id: 'map2',
      name: 'Тронный зал',
      background: '#080a18',
      gridColor: 'rgba(40, 60, 180, 0.15)',
      boss: {
        id: 'dark_knight',
        name: 'Тёмный рыцарь',
        maxHp: 90,
        hp: 90,
        ac: 16,
        actionsPerRound: 2,
        attackBonus: 6,
        canFlee: true,
        startX: 820,
        startY: 360,
        color: '#2c3e50',
        portraitSvg: _bossImg('darkknight'),
        abilities: [
          {
            id: 'dark_slash',
            name: 'Тёмный рубящий удар',
            type: 'attack',
            diceType: 'd10',
            diceCount: 1,
            bonus: 4,
            formula: '1d10 + 4',
            label: 'Бросьте 1d10 + 4 — урон Тёмного удара',
            requiresHitCheck: true,
            targetType: 'hero',
            actionCost: 1,
          },
          {
            id: 'shadow_charge',
            name: 'Теневой натиск',
            type: 'attack',
            diceType: 'd8',
            diceCount: 2,
            bonus: 3,
            formula: '2d8 + 3',
            label: 'Бросьте 2d8 + 3 — урон Теневого натиска',
            requiresHitCheck: true,
            targetType: 'hero',
            actionCost: 2,
          },
          {
            id: 'dark_armor',
            name: 'Чёрная броня',
            type: 'self_buff',
            buffStat: 'damageReduction',
            buffAmount: 3,
            turnsLeft: 2,
            label: 'Чёрная броня: -3 урона на 2 хода',
            requiresHitCheck: false,
            targetType: 'self',
            actionCost: 1,
          },
        ],
      },
    },
    {
      id: 'map3',
      name: 'Некромантова башня',
      background: '#0a0814',
      gridColor: 'rgba(100, 40, 160, 0.15)',
      boss: {
        id: 'necromancer',
        name: 'Некромант',
        maxHp: 120,
        hp: 120,
        ac: 14,
        actionsPerRound: 2,
        attackBonus: 7,
        canFlee: true,
        startX: 820,
        startY: 360,
        color: '#4a235a',
        portraitSvg: _bossImg('necromancer'),
        abilities: [
          {
            id: 'death_bolt',
            name: 'Стрела смерти',
            type: 'attack',
            diceType: 'd8',
            diceCount: 2,
            bonus: 5,
            formula: '2d8 + 5',
            label: 'Бросьте 2d8 + 5 — урон Стрелы смерти',
            requiresHitCheck: true,
            targetType: 'hero',
            actionCost: 1,
          },
          {
            id: 'life_drain',
            name: 'Высасывание жизни',
            type: 'attack_heal',
            diceType: 'd10',
            diceCount: 1,
            bonus: 3,
            formula: '1d10 + 3',
            label: 'Бросьте 1d10 + 3 — урон и исцеление Высасывания',
            requiresHitCheck: true,
            targetType: 'hero',
            actionCost: 2,
            selfHealFraction: 0.5,
          },
          {
            id: 'bone_wall',
            name: 'Костяная стена',
            type: 'self_buff',
            buffStat: 'ac',
            buffAmount: 4,
            turnsLeft: 1,
            label: 'Костяная стена: +4 AC на 1 ход',
            requiresHitCheck: false,
            targetType: 'self',
            actionCost: 1,
          },
        ],
      },
    },
    {
      id: 'map4',
      name: 'Изнанка мира',
      background: '#080408',
      gridColor: 'rgba(180, 20, 20, 0.18)',
      boss: {
        id: 'dark_lord',
        name: 'Тёмный Лорд',
        maxHp: 160,
        hp: 160,
        ac: 18,
        actionsPerRound: 3,
        attackBonus: 9,
        canFlee: false,
        startX: 820,
        startY: 360,
        color: '#7b0000',
        portraitSvg: _bossImg('darklord'),
        abilities: [
          {
            id: 'void_strike',
            name: 'Удар пустоты',
            type: 'attack',
            diceType: 'd12',
            diceCount: 1,
            bonus: 6,
            formula: '1d12 + 6',
            label: 'Бросьте 1d12 + 6 — урон Удара пустоты',
            requiresHitCheck: true,
            targetType: 'hero',
            actionCost: 1,
          },
          {
            id: 'dark_wave',
            name: 'Тёмная волна',
            type: 'attack_aoe',
            diceType: 'd6',
            diceCount: 2,
            bonus: 4,
            formula: '2d6 + 4',
            label: 'Бросьте 2d6 + 4 — урон Тёмной волны (по всем героям)',
            requiresHitCheck: false,
            targetType: 'all_heroes',
            actionCost: 2,
          },
          {
            id: 'soul_crush',
            name: 'Сокрушение духа',
            type: 'attack',
            diceType: 'd10',
            diceCount: 2,
            bonus: 7,
            formula: '2d10 + 7',
            label: 'Бросьте 2d10 + 7 — урон Сокрушения духа',
            requiresHitCheck: true,
            targetType: 'hero',
            actionCost: 2,
          },
          {
            id: 'dark_regeneration',
            name: 'Тёмное восстановление',
            type: 'self_heal',
            healAmount: 15,
            label: 'Тёмное восстановление: +15 HP',
            requiresHitCheck: false,
            targetType: 'self',
            actionCost: 1,
          },
        ],
      },
    },
  ],

  diceIcons: {
    d4:  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><polygon points="12,2 22,20 2,20" fill="#1a1200" stroke="#c8a000" stroke-width="1.5"/><text x="12" y="18" text-anchor="middle" font-size="7" fill="#c8a000" font-family="sans-serif">4</text></svg>`,
    d6:  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><rect x="3" y="3" width="18" height="18" rx="3" fill="#1a1200" stroke="#c8a000" stroke-width="1.5"/><text x="12" y="16" text-anchor="middle" font-size="8" fill="#c8a000" font-family="sans-serif">6</text></svg>`,
    d8:  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><polygon points="12,2 22,10 18,22 6,22 2,10" fill="#1a1200" stroke="#c8a000" stroke-width="1.5"/><text x="12" y="17" text-anchor="middle" font-size="7" fill="#c8a000" font-family="sans-serif">8</text></svg>`,
    d10: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><polygon points="12,2 20,8 22,17 12,22 2,17 4,8" fill="#1a1200" stroke="#c8a000" stroke-width="1.5"/><text x="12" y="17" text-anchor="middle" font-size="6" fill="#c8a000" font-family="sans-serif">10</text></svg>`,
    d12: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><polygon points="12,2 19,5 22,12 19,19 12,22 5,19 2,12 5,5" fill="#1a1200" stroke="#c8a000" stroke-width="1.5"/><text x="12" y="16" text-anchor="middle" font-size="6" fill="#c8a000" font-family="sans-serif">12</text></svg>`,
    d20: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><polygon points="12,1 20,6 23,14 18,21 6,21 1,14 4,6" fill="#1a1200" stroke="#c8a000" stroke-width="1.5"/><text x="12" y="16" text-anchor="middle" font-size="6" fill="#c8a000" font-family="sans-serif">20</text></svg>`,
  },
};
